map_type: costmap
obstacle_range: 0.9
raytrace_range: 2.5
transform_tolerance: 0.2
inflation_radius: 1.50
cost_scaling_factor: 2.58
path_distance_bias: 32.0
goal_distance_bias: 20.0
occdist_scale: 0.02
sim_time: 4.0
cost_factor: 0.55
neutral_cost: 66
lethal_cost: 255
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
